menu:
  主页: /
  时间轴: /archives/
  标签: /tags/
  关于我: /about/

author: Rex
subtitle: 记录模型产出、实验过程与协作结果
avatar: https://qiniu.wzhecnu.cn/PicBed5/images_for_blogs/avatar.jpg
favicon: /img/favicon.png
root_url:
since: 2020

subnav:
  GitHub: https://github.com/RexWzh
  bilibili: https://space.bilibili.com/518870168
  知乎: https://www.zhihu.com/people/wang-zhi-hong-79-21
  RSS: /atom.xml

preload_comment: false
show_count: false

background_image: 0
base_font_size: 17

copyright: true

toc:
  on: true
  list_number: true
  max_depth: 3
  nowrap: false

animate: true
jquery_ui: false
tagcloud: true
friends: false
aboutme: 记录模型产出、实验过程与长期沉淀。

open_in_new:
  global: 0
  title: false
  post: true
  tags: false
  categories: false
  article_nav: false
  archives: true
  mini_archives: true
  menu: false
  friends: true
  socail: true

rss: /atom.xml

ie_updater:
  on: true
  link: //outdatedbrowser.com/

tab_title_change:
  on: false
  left_tab_title: '(つェ⊂) 我藏好了哦~ '
  return_tab_title: '(*´∇｀*) 被你发现啦~ '

search:
  on: true
  onload: false

fancybox: true
mathjax: true

share:
  on: true
  baidu: true
  addthis: false
  addthis_pubid: 'ra-56ff76c972fc0cf9'

visit_counter:
  on: true
  site_visit: true
  page_visit: true

github_widget: false

progressBar:
  on: true
  type: 'minimal'
  color: blue

CDN:
  jquery: https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js
  require: https://cdn.jsdelivr.net/npm/requirejs@2.3.7/require.min.js
  fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
  fancybox_js: https://cdn.jsdelivr.net/npm/fancybox@2.1.7/source/jquery.fancybox.pack.js
  fancybox_css: https://cdn.jsdelivr.net/npm/fancybox@2.1.7/source/jquery.fancybox.css
  animate_css: https://cdn.jsdelivr.net/npm/animate.css@3.7.2/animate.min.css
  jquery_ui_js: https://cdn.jsdelivr.net/npm/jquery-ui-dist@1.13.3/jquery-ui.min.js
  jquery_ui_css: https://cdn.jsdelivr.net/npm/jquery-ui-dist@1.13.3/jquery-ui.min.css
  pace_js: https://cdn.jsdelivr.net/npm/pace-js@1.2.4/pace.min.js
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2.0.11/dist/clipboard.min.js
  mathjax: https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js
  scrollreveal: https://cdn.jsdelivr.net/npm/scrollreveal@3.4.0/dist/scrollreveal.min.js
